### ISSUE TITLE
Consulta sobre configuración de modulo

### ISSUE THREAD

**Issue by lgaticaq** [saavedrajl/cellocator-decodes#2]
Consulta, sabes como configurar el modulo CR300B y/o Cello IQ?
Es necesario tener algún archivo que cargar en el programa que se ejecuta en windows?

**Comment by jldamians** [comment]
Es necesario un archivo de configuración llamado PL, donde están las configuraciones del GPS. Este archivo luego tendrá que ser cargado al GPS.

**Comment by lgaticaq** [comment]
Ese archivo desde donde se obtiene, o tiene que ser generado con el mismo programa?

**Comment by jldamians** [comment]
Si mal no recuerdo, al comprar equipos Cellocator te dan accesos a su plataforma, desde donde puedes descargar esos archivos. Luego solo es cuestión de cambiar los parámetros que necesites o no te sean utiles.
