### ISSUE TITLE
Parsear varios datos en un mismo Buffer

### ISSUE THREAD

**Issue by lgaticaq** [saavedrajl/cellocator-decodes#3]
Hola te a tocado parsear varios datos en una misma trama que llega por TCP. Ejemplo:

``` js
var raw = new Buffer('4d43475000b8ac1100081824eb2904151d00450123b300002968defe980000005c530524c7420000a00000000000000000000000000000000000000000001921050e010000f34d43475000b8ac1100081825eb2904151d00410021b300812967e5fe970000005c530524c7420000a00000000000000000000000000000000000000000002321050e0100007d4d43475000b8ac1100081826eb2904151d00310023b308802966e5fe970000005c530524c7420000a00000000000000000000000000000000000000000002621050e010000794d43475000b8ac1100081827eb2904151d002c0023b300802966e6fe970000005c530524c7420000a00000000000000000000000000000000000000000002921050e010000714d43475000b8ac1100081828eb2904151d004100', 'hex');
```

Me pasa de vez en cuando que llegan datos así desde el modulo. Quisiera saber si existe alguna opción para que no pase eso.

Saludos

**Comment by jldamians** [comment]
En ese caso, me ha tocado identificar cuantas tramas vienen sumarizadas en una misma para luego recorrerlas, asumiendo que cada trama válida es una transmisión normal. Para cada trama se tendrá que enviar el ACK

**Comment by jldamians** [comment]
Puedes ver la función splitTrama en https://github.com/saavedrajl/cellocator-decodes/blob/master/lib/utils/handleTrama.js

**Comment by lgaticaq** [comment]
Gracias :+1:
